### Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde

In [1]:
import numpy as np

In [2]:
def ATV(x,N,increasing=False):
    x=np.array(x)
    if increasing:
        return np.column_stack([x**(i) for i in range(N)])
    return np.column_stack([x**(N-1-i) for i in range(N)])
print("For Increasing Order")
print(ATV([1,2,3,4,5],5,increasing=True))
print("-"*30)
print("For Decreasing Order")
print(ATV([1,2,3,4,5],5))

For Increasing Order
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
------------------------------
For Decreasing Order
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


### Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of

the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a 
window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.



In [3]:
def movingAverage(arr,K):
    N=len(arr)
    cumSum=np.cumsum(arr)
    for i in range(N-K+1):
        if i==0:
            ans=cumSum[K-1]
        else:
            ans=cumSum[i+K-1]-cumSum[i-1]
            
        print("window {} is {}".format(i+1,ans/K))
    
movingAverage([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] ,3)

window 1 is 5.0
window 2 is 4.666666666666667
window 3 is 5.666666666666667
window 4 is 6.666666666666667
window 5 is 9.666666666666666
window 6 is 28.666666666666668
window 7 is 49.333333333333336
window 8 is 72.66666666666667
window 9 is 84.0
window 10 is 93.33333333333333
window 11 is 116.33333333333333
